version: 0.2
phases:
  build:
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
      - ls
      - docker build -t test-cont .
      - docker run -dp 4444:4444 test-cont
      - docker ps

artifacts:
  files:
    - ./**/*
